services:
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8001:8000"
    environment:
      LINK_TTL_SECONDS: ${LINK_TTL_SECONDS}
      REDIS_URL: redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app

  test:
      build: .
      command: pytest -v
      environment:
        REDIS_URL: redis://redis:6379
        LINK_TTL_SECONDS: "86400"
      depends_on:
        redis:
          condition: service_healthy
      volumes:
        - .:/app

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
